import { Landmark } from '../types';

export const landmarks: Landmark[] = [
  {
    id: 'truth',
    name: 'Search for Truth',
    description: 'Unveiled on April 5, 1984, by then-ViSCA President Dr. Fernando A. Bernardo. The monument features two gigantic, unclad figures of a man and a woman standing prominently on an elevated platform right in front of the Administration Building. The total design and its specific structural platform layout were executed with the guidance of Dr. Bernardo. It serves as the ultimate visual emblem and grounds the university\'s core philosophy the relentless academic pursuit of excellence and knowledge.',
    icon: 'compass',
    order: 1,
    label: 'Landmark 01',
    photoUrl: '/landmarks/vsu-admin.jpg',
    photoUrls: ['/landmarks/vsu-admin.jpg'],
    zoneType: 'building',
    zoneRadius: 80,
    mapX: 50,
    mapY: 8.33,
    flavorText: "The core emblem of VSU's academic pursuit",
    funFact: "Contrary to common public speculation, the monument was not inspired by the Philippine mythical figures Malakas and Maganda. Instead, the nudity of the figures is an artistic choice symbolizing boldness, unencumbered freedom, and total impartiality in the academic quest for truth. "
  },
  {
    id: 'japanese_garden',
    name: 'Japanese Garden',
    description: 'Established during the administration of Dr Jose L. Bacusmo as a physical manifestation of international academic linkages and cross-cultural partnerships (promoted extensively through the Philippine Association of Japanese Government Scholars). It offers a peaceful, contemplative oasis for relaxation, meditation, and aesthetic appreciation, symbolizing international solidarity and friendship.',
    icon: 'flower',
    order: 2,
    label: 'Landmark 02',
    photoUrl: '/landmarks/vsu-japanese-garden.jpg',
    photoUrls: ['/landmarks/vsu-japanese-garden.jpg'],
    zoneType: 'green',
    zoneRadius: 100,
    mapX: 20,
    mapY: 25.0,
    flavorText: 'A tranquil sanctuary of peace and reflection',
    funFact: 'The garden directly honors the strong educational ties between VSU and various Japanese institutions of higher learning, housing several scholars who completed their advanced degrees in Japan and brought back specialized agricultural and ecological techniques to Leyte.'
  },
  {
    id: 'ecopark',
    name: 'Eco-park',
    description: 'Developed as an open-air ecological hub and multi-use recreational space to highlight VSU\'s commitment to environmental sustainability and green campus living during the administration of Dr. Paciencia P. Milan. Positioned on relatively flat terrain that bridges academic buildings along VSU\'s "Mall" with open green spaces. A vibrant community gathering space frequently utilized for open-air university events, student-led agricultural and culinary expositions and leisure walks.',
    icon: 'nature_people',
    order: 3,
    label: 'Landmark 03',
    photoUrl: '/landmarks/vsu-ecopark.jpg',
    photoUrls: ['/landmarks/vsu-ecopark.jpg'],
    zoneType: 'green',
    zoneRadius: 75,
    mapX: 68,
    mapY: 41.67,
    flavorText: 'A lush sanctuary for nature and conservation',
    funFact: 'The Eco-park functions as a living laboratory for sustainable landscaping; the flora here is intentionally curated to be drought-tolerant, requiring virtually zero artificial watering during the wet season and minimal upkeep during dry months, aligning closely with global climate action initiatives.'
  },
  {
    id: 'obelisk',
    name: 'VSU Mall and Obelisk',
    description: 'Erected between the late 1970\'s to 80\'s the twin obelisks serve as the institutional threshold of the university at the main entry gate, anchoring the commercial and historical crossroads known locally as the VSU Mall area. The southern obelisk features the artistic relief of the "god of the sun" (representing agriculture and allied disciplines), while the northern obelisk features the "god of lightning and thunder" (representing technology, engineering, and innovation). The adjacent VSU Mall zone serves as an open public pocket plaza surrounded by commercial stalls and student services.',
    icon: 'verified',
    order: 4,
    label: 'Landmark 04',
    photoUrl: '/landmarks/vsu-obelisk-1.jpg',
    photoUrls: ['/landmarks/vsu-obelisk-1.jpg', '/landmarks/vsu-obelisk-2.jpg', '/landmarks/vsu-obelisk-3.jpg'],
    zoneType: 'open',
    zoneRadius: 70,
    mapX: 30,
    mapY: 58.33,
    flavorText: 'A historic beacon of VSU pride and entry',
    funFact: 'The architectural iconography of the twin obelisks was deliberately mapped out to encapsulate VSU’s dual historical identity: an elite powerhouse in agricultural sciences paired dynamically with modern industrial technology and computing advancements.'
  },
  {
    id: 'frog_fountain',
    name: 'Frog Fountain',
    description: 'Created between the 1950\'s and 1960\'s as a whimsical and iconic landmark deeply embedded in the everyday student life and spatial navigation of the lower campus. A functional water fountain structure distinctively adorned with sculptural frog figures acting as water spouts, surrounded by matching circular retaining structures and seasonal flowering beds.',
    icon: 'droplets',
    order: 5,
    label: 'Landmark 05',
    photoUrl: '/landmarks/vsu-frog-fountain-1.jpg',
    photoUrls: ['/landmarks/vsu-frog-fountain-1.jpg', '/landmarks/vsu-frog-fountain-2.jpg'],
    zoneType: 'water',
    zoneRadius: 90,
    mapX: 65,
    mapY: 75.0,
    flavorText: "A playful splash of VSU's historic charm",
    funFact: 'Despite its modest size compared to monumental structures like the Obelisk, the Frog Fountain is one of the most enduring informal geographic markers used by generations of Viscans for giving campus directions ("Magkita ta sa Frog Fountain") and conjures happy memories from the alumni as a drinking fountain ("Naka-kiss sa Baki").'
  },
  {
    id: 'beach',
    name: 'VSU Beach',
    description: 'A natural coastal feature integrated into the university grounds since the institution\'s inception, preserved as part of VSU\'s unique identity as a "resort university". Bounded entirely by the tranquil waters of the Camotes Sea on its western coast, receiving direct freshwater influxes from cooling river systems flowing down from Mt. Pangasugan (such as the Pangasugan River). It is widely celebrated for offering some of the most breathtaking, unobstructed gold-and-crimson sunset views in the entire region. It acts as a recreational retreat where students and visitors can swim, unwind, or hold seaside academic and social gatherings.',
    icon: 'beach_access',
    order: 6,
    label: 'Landmark 06',
    photoUrl: '/landmarks/vsu-beach.jpg',
    photoUrls: ['/landmarks/vsu-beach.jpg'],
    zoneType: 'water',
    zoneRadius: 95,
    mapX: 48,
    mapY: 91.67,
    flavorText: 'Camotes Sea breezes meeting tropical sunsets',
    funFact: 'VSU is structurally unique in the Philippines for being a premier academic institution whose campus stretches uninterrupted "from mountain peak to sea" spanning from the dense tropical rainforest canopy of Mt. Pangasugan all the way down to the shoreline of the Camotes Sea.'
  }
];
