import { Landmark } from '../types';

export const landmarks: Landmark[] = [
  {
    id: 'admin',
    name: 'Admin Bldg',
    description: 'A grand, classical university administration building with large white columns and a wide staircase. The building is bathed in warm afternoon sunlight, projecting institutional prestige.',
    icon: 'account_balance',
    order: 1,
    label: 'Landmark 01',
    photoUrl: '/public/landmarks/vsu-admin.jpg',
    zoneType: 'building',
    zoneRadius: 80,
    mapX: 50,
    mapY: 8.33,
    flavorText: "The heart of VSU's academic life",
    funFact: "The administration building stands at the direct center of VSU's radial design layout."
  },
  {
    id: 'ecopark',
    name: 'VSU Eco Park',
    description: 'A lush green sanctuary showing off rich tropical biodiversity, winding forest trails, and educational conservation spaces. Perfect for deep reflections on ecology and sustainable development.',
    icon: 'nature_people',
    order: 2,
    label: 'Landmark 02',
    photoUrl: '/public/landmarks/vsu-ecopark.jpg',
    zoneType: 'green',
    zoneRadius: 100,
    mapX: 20,
    mapY: 25.0,
    flavorText: 'A lush sanctuary for nature and conservation',
    funFact: "It contains rare, native orchid collections and a century-old tropical canopy walk."
  },
  {
    id: 'library',
    name: 'VSU Library',
    description: 'A modern, multi-story university library building featuring large glass windows reflecting the surrounding nature. It serves as a center for quiet academic study and active learning.',
    icon: 'local_library',
    order: 3,
    label: 'Landmark 03',
    photoUrl: '/public/landmarks/vsu-library.jpg',
    zoneType: 'building',
    zoneRadius: 75,
    mapX: 68,
    mapY: 41.67,
    flavorText: 'A quiet harbor for wisdom and knowledge.',
    funFact: "The VSU Library holds over 80,000 volumes and is the largest academic library in Eastern Visayas."
  },
  {
    id: 'obelisk',
    name: 'VSU Obelisk',
    description: 'Standing as a proud symbol of the university, the Obelisk marks the entrance to the lower campus. It represents the enduring pursuit of agricultural and environmental excellence.',
    icon: 'verified',
    order: 4,
    label: 'Landmark 04',
    photoUrl: '/public/landmarks/vsu-obelisk.jpg',
    zoneType: 'open',
    zoneRadius: 70,
    mapX: 30,
    mapY: 58.33,
    flavorText: 'A historic beacon of agricultural excellence',
    funFact: "The obelisk is a 12-meter tall concrete spire representing VSU's pillars of excellence."
  },
  {
    id: 'oval',
    name: 'VSU Oval',
    description: 'The historic sports athletic field where student-athletes train and compete. Ringed by trees, it represents the energetic spirit and dynamic campus community of VSU.',
    icon: 'stadium',
    order: 5,
    label: 'Landmark 05',
    photoUrl: '/public/landmarks/vsu-oval.jpg',
    zoneType: 'sports',
    zoneRadius: 90,
    mapX: 65,
    mapY: 75.0,
    flavorText: 'The energetic hub of sports and student spirit',
    funFact: "It features an all-weather rubberized athletic track host to regional matches."
  },
  {
    id: 'beach',
    name: 'VSU Beach',
    description: 'A gorgeous coastline overlooking the Camotes Sea, known for its relaxing sea breezes and dramatic sunset views. It is a favorite spot for student relaxation and recreational events.',
    icon: 'beach_access',
    order: 6,
    label: 'Landmark 06',
    photoUrl: '/public/landmarks/vsu-beach.jpg',
    zoneType: 'water',
    zoneRadius: 95,
    mapX: 48,
    mapY: 91.67,
    flavorText: 'Camotes Sea breezes meeting tropical sunsets',
    funFact: "The beachfront is the perfect venue for witnessing Camotes Sea's golden-hour sunsets."
  }
];
